name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: moneymanager
          POSTGRES_PASSWORD: moneymanager
          POSTGRES_DB: moneymanager
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - name: Build and Run Docker Compose
    - run: |
        docker-compose build
        docker-compose up --detach
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        docker-compose exec money-manager cd moneymanager && python manage.py test
